version: "3.7"

services:
  base:
    build:
      context: .
      dockerfile: docker/base.Dockerfile
    image: alvar-map-base

  node:
    build:
      context: .
      dockerfile: docker/node.Dockerfile
    depends_on:
      - base
    image: alvar-map-node

  postgres:
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    restart: always
    depends_on:
      - base
    container_name: alvar-map-postgres
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      # host_port:container_port
      # If you want to expose the Postgres to 4001 port in host machine, write "4001:5432"
      - "4321:5432"

volumes:
  postgres:
