version: 2.1
parameters:
  wait-index:
    type: string
    default: "0"
  start:
    type: boolean
    default: true
  wait:
    type: boolean
    default: false
  deploy:
    type: boolean
    default: false

workflows:
  start_install:
    when: << pipeline.parameters.start >>
    jobs:
      - start_install
      - wait_for_install:
          requires:
            - start_install

  wait_for_install:
    when: << pipeline.parameters.wait >>
    jobs:
      - wait_for_install

  finish_install_and_deploy:
    when: << pipeline.parameters.deploy >>
    jobs:
      - finish_install
      - deploy:
          type: approval
          requires:
            - finish_install

jobs:
  start_install:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      - run: |
          echo "Install"

  wait_for_install:
    docker:
      - image: circleci/python:3.8
    environment:
      WAIT_INDEX: << pipeline.parameters.wait-index >>
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Wait for install
          command: |
            if [ $WAIT_INDEX -lt 2 ]
            then
              echo "Installation still in progress, waiting .."
              sleep 5
              NEW_WAIT_INDEX=$((WAIT_INDEX+1))
              body_template='{
                "parameters": {
                  "start": false,
                  "wait": true,
                  "wait-index": "%s"
                }
              }'
              body=$(printf "$body_template" "$NEW_WAIT_INDEX")
              echo "Sending body: $body"
              curl -vv --fail -u ${CIRCLECI_TOKEN}: -X POST --header "Content-Type: application/json" -d "$body" https://circleci.com/api/v2/project/git/alvarcarto/alvarcarto-map-server/pipeline
            else
              echo "Installation done, launching further steps"
              body='{
                "parameters": {
                  "start": false,
                  "deploy": true
                }
              }'

              echo "Sending body: $body"
              curl -vv --fail -u ${CIRCLECI_TOKEN}: -X POST --header "Content-Type: application/json" -d "$body" https://circleci.com/api/v2/project/git/alvarcarto/alvarcarto-map-server/pipeline
            fi

  finish_install:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            echo "Install"

  deploy:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      - deploy:
          name: Deploy
          command: |
            echo "Deploy"
