version: 2.1
parameters:
  wait:
    type: boolean
    default: false
  deploy:
    type: boolean
    default: false

workflows:
  commit:
    jobs:
      - start_install
      - wait_for_install

  finish_install_and_deploy:
    when: << pipeline.parameters.deploy >>
    jobs:
      - finish_install
      - deploy:
          type: approval
          requires:
            - finish_install

jobs:
  start_install:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      - run: |
          echo "Install"

  wait_for_install:
    docker:
      - image: circleci/python:3.8
    environment:
      WAIT_INDEX: << pipeline.parameters.wait-index >>
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Wait for install
          command: |
            if [ $WAIT_INDEX -lt 2 ]
            then
              NEW_WAIT_INDEX=$((WAIT_INDEX+1))
              BODY="{
                "parameters": {
                  "deploy": "$NEW_WAIT_INDEX"
                }
              }"
              curl -u ${CIRCLECI_TOKEN}: -X POST --header "Content-Type: application/json" -d "$BODY" https://circleci.com/api/v2/project/git/alvarcarto/alvarcarto-map-server/pipeline
            else
              curl -u ${CIRCLECI_TOKEN}: -X POST --header "Content-Type: application/json" https://circleci.com/api/v2/project/git/alvarcarto/alvarcarto-map-server/pipeline
            fi

  finish_install:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            echo "Install"

  deploy:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout

      - deploy:
          name: Deploy
          command: |
            echo "Deploy"
